CREATE TABLE candidate (
   candidateID integer primary key,
   userID integer REFERENCES user_table(id),   
   first_name varchar(500),
   last_name varchar(500),
   contact_no integer,
   date_of_birth date,
   email varchar(500),
   genderID integer REFERENCES gender(genderid), 
   permanent_address varchar(500),
   permanent_ad_countryID integer REFERENCES country(countryid), 
   permanent_ad_stateID integer REFERENCES state(stateid), 
   permanent_ad_districtID integer REFERENCES district(districtid), 
   permanent_ad_pincode integer,
   residential_address varchar(500),
   residential_ad_countryID integer REFERENCES country(countryid), 
   residential_ad_stateID integer REFERENCES state(stateid), 
   residential_ad_districtID integer REFERENCES district(districtid), 
   residential_ad_pincode integer,
   religionID integer REFERENCES religion(religionid),
   casteID integer REFERENCES caste(casteid), 
   subcasteid integer REFERENCES sub_caste(subcasteid),
   education_id integer REFERENCES highest_education(educationid),
   mother_toungid integer REFERENCES mother_tongue(languageid),
   height integer,
   color_complexionid integer REFERENCES color_complexion(colorid),
   family_typeid integer REFERENCES family_type(family_typeid)
) ;