CREATE ROLE mangalam_app WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'xxxxxx';
COMMENT ON ROLE mangalam_app IS 'user for mangalam app';

REVOKE ALL
ON ALL TABLES IN SCHEMA public 
FROM mangalam_app;


GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO mangalam_app;




